# -*- coding: utf-8 -*-
"""ItemKNN_LensKit_ML10M_Automated Fine tuned+K fold.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9sTOPfQlIWyNAoqY2w0JOpEE5sgE4gC
"""

!pip install lenskit

from lenskit import batch, topn, util
from lenskit import crossfold as xf
from lenskit.algorithms import Recommender, item_knn as knn  # Import UserKNN
from sklearn.model_selection import train_test_split
import pandas as pd
from lenskit.datasets import ML10M
import seedbank

# Initialize seed
seedbank.initialize(1)

# Function to down-sample the dataset
def downsample_data(ratings, percentage):
    sampled_ratings = ratings.sample(frac=percentage, random_state=1)
    return sampled_ratings

# Function to filter low interaction users and items
def filter_low_interaction(ratings, min_user_interactions=5, min_item_interactions=5):
    user_counts = ratings['user'].value_counts()
    item_counts = ratings['item'].value_counts()
    filtered_ratings = ratings[ratings['user'].isin(user_counts[user_counts >= min_user_interactions].index) &
                               ratings['item'].isin(item_counts[item_counts >= min_item_interactions].index)]
    return filtered_ratings

# Load and preprocess the dataset
file_path = '/content/drive/MyDrive/Master Thesis/Dataset/ml-10m'
ml10m = ML10M(file_path)
ratings = ml10m.ratings
ratings = ratings.dropna(subset=['rating'])
# Handle duplicate ratings by averaging them
ratings = ratings.groupby(['user', 'item']).agg({'rating': 'mean'}).reset_index()
print(ratings.head())
# Filter users and items with low interactions
ratings = filter_low_interaction(ratings, min_user_interactions=5, min_item_interactions=5)

# Split into train and test sets
train_data, test_data = train_test_split(ratings, test_size=0.1, random_state=1)

# Down-sample the training data
train_data = downsample_data(train_data, percentage=0.1)

# Function to evaluate with nDCG metric
def evaluate_with_ndcg(aname, algo, train, valid):
    fittable = util.clone(algo)
    fittable = Recommender.adapt(fittable)
    fittable.fit(train)
    users = valid.user.unique()
    recs = batch.recommend(fittable, users, 10)
    recs['Algorithm'] = aname
    return recs

# Perform k-fold cross-validation for different values of K and compute nDCG
results = []
best_k = None
best_mean_ndcg = -float('inf')

for k in [1, 2, 5, 6, 10, 100]:  # Iterate over K values from 1 to 20
    seedbank.initialize(1)
    algo_ii = knn.ItemItem(k)  # Use ItemItem instead of ItemItem
    all_recs = []
    valid_data = []

    for train, valid in xf.partition_users(train_data[['user', 'item', 'rating']], 5, xf.SampleFrac(0.2), rng_spec=1):
        valid_data.append(valid)
        all_recs.append(evaluate_with_ndcg('ItemItem', algo_ii, train, valid))  # Use 'ItemItem' as the algorithm name

    all_recs = pd.concat(all_recs, ignore_index=True)
    valid_data = pd.concat(valid_data, ignore_index=True)

    rla = topn.RecListAnalysis()
    rla.add_metric(topn.ndcg)
    fold_results = rla.compute(all_recs, valid_data)

    # Calculate mean nDCG directly from fold_results
    mean_ndcg = fold_results['ndcg'].mean()
    results.append({'K': k, 'Mean nDCG': mean_ndcg})

    if mean_ndcg > best_mean_ndcg:
        best_mean_ndcg = mean_ndcg
        best_k = k

# Print results
print("Results:")
for result in results:
    print(f"K = {result['K']}: Mean nDCG = {result['Mean nDCG']:.4f}")

print(f"\nBest K: {best_k} (Mean nDCG = {best_mean_ndcg:.4f})")

# Fit the algorithm on the full training data with the best K
algo_ii_best = knn.ItemItem(1)  # Use ItemItem instead of ItemItem
algo_ii_full = Recommender.adapt(util.clone(algo_ii_best))
algo_ii_full.fit(train_data)

# Get the unique users from the test data
test_users = test_data.user.unique()


# Generate recommendations for the test users with batch processing
test_recs = batch.recommend(algo_ii_full, test_users, 10)
test_recs['Algorithm'] = 'ItemItem'

# Evaluate the recommendations using the test set
test_rla = topn.RecListAnalysis()
test_rla.add_metric(topn.ndcg)
test_results = test_rla.compute(test_recs, test_data)

# Display the evaluation results
print(test_results.head())
print("NDCG mean for test set:", test_results.groupby('Algorithm').ndcg.mean())