# -*- coding: utf-8 -*-
"""Plot_Movielens10M_Best perfotmance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTPuclHby_gKZV6l3k9mwRnthiZXzkQW
"""

import pandas as pd
import matplotlib.pyplot as plt

# Example results
data = {
    'Percentage': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    'FunkSVD': [0.0253, 0.0264, 0.0266, 0.0278, 0.0285, 0.0291, 0.0300, 0.0308, 0.0318, 0.0324],
    'UserKNN': [0.0010, 0.0007, 0.0005, 0.0006, 0.0007, 0.0008, 0.0010, 0.0012, 0.0013, 0.0016],
    'ItemKNN': [0.0036, 0.0031, 0.0034, 0.0036, 0.0044, 0.0056, 0.0079, 0.0093, 0.0105, 0.0121],
    'ALS':[0.022, 0.0239, 0.0260, 0.0275, 0.0288, 0.0287, 0.0293, 0.0302, 0.0311, 0.0326],
    'Popular': [0.0525, 0.0552, 0.0583, 0.0615, 0.0656, 0.0701, 0.0751, 0.0813, 0.0886, 0.0979],
    'Bias': [0.0329, 0.0325, 0.0319, 0.0322, 0.0331, 0.0340, 0.0346, 0.0366, 0.0363, 0.0392],
    'Random': [0.0010, 0.0009, 0.0008, 0.0010, 0.0009, 0.0011, 0.0009, 0.0009, 0.0009, 0.0009]
}

df = pd.DataFrame(data)
print(df)

plt.figure(figsize=(14, 8))
plt.style.use('seaborn-darkgrid')

# Plot each algorithm's nDCG values
for algorithm in df.columns[1:]:
    plt.plot(df['Percentage'], df[algorithm], marker='o', linestyle='-', linewidth=2, label=algorithm)

# Add title and labels
plt.title('Movielens 10M', fontsize=16)
plt.xlabel('Percentage of Dataset Used', fontsize=14)
plt.ylabel('nDCG @ 10 Score', fontsize=14)
plt.xticks(df['Percentage'])
plt.yticks(fontsize=12)

# Add a legend
plt.legend(title='Algorithm', fontsize=12)

# Show the plot
plt.grid(True)
plt.show()