# -*- coding: utf-8 -*-
"""Plot_Movielens100K.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_XehwVXqUq-2ypLeFTVyVKncCOy6Vf7
"""

import pandas as pd
import matplotlib.pyplot as plt

# Example results
data = {
    'Percentage': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    'FunkSVD': [0.0014,0.0039,0.0009,0.0015,0.0009,0.0023,0.0046,0.0047,0.0040,0.0048],
    'UserKNN': [0.0076,0.0047,0.0004,0.0035,0.0013,0.0006,0.0011,0.0013,0.0011,0.0015],
    'ItemKNN': [0.0087,0.0071,0.0045,0.0059,0.0078, 0.0077,0.0086,0.0133,0.0119,0.0168],
    'ALS':[0.0136,0.0164,0.0220,0.0249,0.0297,0.0280,0.0313,0.0319,0.0405, 0.0402]
}

df = pd.DataFrame(data)
print(df)

plt.figure(figsize=(14, 8))
plt.style.use('seaborn-darkgrid')

# Plot each algorithm's nDCG values
for algorithm in df.columns[1:]:
    plt.plot(df['Percentage'], df[algorithm], marker='o', linestyle='-', linewidth=2, label=algorithm)

# Add title and labels
plt.title('Movielens 100K', fontsize=16)
plt.xlabel('Percentage of Dataset Used', fontsize=14)
plt.ylabel('nDCG Score', fontsize=14)
plt.xticks(df['Percentage'])
plt.yticks(fontsize=12)

# Add a legend
plt.legend(title='Algorithm', fontsize=12)

# Show the plot
plt.grid(True)
plt.show()