# -*- coding: utf-8 -*-
"""Plot_ML1M.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FpAEGIzqEAgQoICmU4FB4CCbsuGZxy-Y
"""

import pandas as pd
import matplotlib.pyplot as plt

# Example results
data = {
    'Percentage': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    'FunkSVD': [0.0003,0.0005,0.0004,0.0005,0.0002,0.0002,0.0001,0.0001,0.0001,0.0002],
    'UserKNN': [0.0015,0.0005,0.0002,0.0002,0.0003, 0.0006,0.0009,0.0016,0.0036,0.0032],
    'ItemKNN': [0.0036,0.0026,0.0022,0.0015,0.0020,0.0057,0.0056,0.0074,0.0099,0.0112],
    'ALS':[0.0141,0.0151,0.0156,0.0177,0.0201,0.0236,0.0248,0.0279,0.0314,0.0339]
}

df = pd.DataFrame(data)
print(df)

plt.figure(figsize=(14, 8))
plt.style.use('seaborn-darkgrid')

# Plot each algorithm's nDCG values
for algorithm in df.columns[1:]:
    plt.plot(df['Percentage'], df[algorithm], marker='o', linestyle='-', linewidth=2, label=algorithm)

# Add title and labels
plt.title('Movielens 1M', fontsize=16)
plt.xlabel('Percentage of Dataset Used', fontsize=14)
plt.ylabel('nDCG Score', fontsize=14)
plt.xticks(df['Percentage'])
plt.yticks(fontsize=12)

# Add a legend
plt.legend(title='Algorithm', fontsize=12)

# Show the plot
plt.grid(True)
plt.show()