# -*- coding: utf-8 -*-
"""Plot_Toys and Games.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xp7WUZaztZhTOHfNWcDcBsJFIcDvS-Wg
"""

import pandas as pd
import matplotlib.pyplot as plt

# Example results
data = {
    'Percentage': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    'FunkSVD': [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001],
    'UserKNN': [0.0003, 0.0004,0.0005,0.0005,0.0005,0.0006,0.0007,0.0008,0.0007,0.0006],
    'ItemKNN': [0.0043,0.0049,0.0051,0.0053,0.0048,0.0042,0.0038,0.0035, 0.0029,0.0026],
    'ALS':[0.0016, 0.0011, 0.0013, 0.0010,0.0009,0.0009, 0.0008, 0.0009, 0.0009, 0.0010 ]
}

df = pd.DataFrame(data)
print(df)

plt.figure(figsize=(14, 8))
plt.style.use('seaborn-darkgrid')

# Plot each algorithm's nDCG values
for algorithm in df.columns[1:]:
    plt.plot(df['Percentage'], df[algorithm], marker='o', linestyle='-', linewidth=2, label=algorithm)

# Add title and labels
plt.title('Amazon Toys and Games', fontsize=16)
plt.xlabel('Percentage of Dataset Used', fontsize=14)
plt.ylabel('nDCG Score', fontsize=14)
plt.xticks(df['Percentage'])
plt.yticks(fontsize=12)

# Add a legend
plt.legend(title='Algorithm', fontsize=12)

# Show the plot
plt.grid(True)
plt.show()