# -*- coding: utf-8 -*-
"""ALS_LensKit_ML100K_Automated Fine tuned+K fold.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z-VPxLGYY0__Y7rJTLqQZiRFPBL6-LnY
"""

!pip install lenskit

from lenskit import batch, topn, util
from lenskit import crossfold as xf
from lenskit.algorithms import Recommender
from lenskit.algorithms.als import BiasedMF  # Import ALS algorithm
from sklearn.model_selection import train_test_split
import pandas as pd
from lenskit.datasets import ML100K
import seedbank

# Initialize seed
seedbank.initialize(1)

# Function to down-sample the dataset
def downsample_data(ratings, percentage):
    sampled_ratings = ratings.sample(frac=percentage, random_state=1)
    return sampled_ratings

# Load and preprocess the dataset
file_path = '/content/drive/MyDrive/Master Thesis/Dataset/ml-100k'
ml100k = ML100K(file_path)
ratings = ml100k.ratings

# Split into train and test sets
train_data, test_data = train_test_split(ratings, test_size=0.1, random_state=1)

# Down-sample the training data
train_data = downsample_data(train_data, percentage=0.2)

# Function to evaluate with nDCG metric
def evaluate_with_ndcg(aname, algo, train, valid):
    fittable = util.clone(algo)
    fittable = Recommender.adapt(fittable)
    fittable.fit(train)
    users = valid.user.unique()
    recs = batch.recommend(fittable, users, 10)
    recs['Algorithm'] = aname
    return recs

# Perform k-fold cross-validation for different values of features and compute nDCG
results = []
best_features = None
best_mean_ndcg = -float('inf')

feature_values = [20, 30, 40, 50, 60, 70, 80, 90, 100]  # Define a range of feature values to test

for features in feature_values:
    seedbank.initialize(1)
    algo_als = BiasedMF(features=features, iterations=10, reg=0.1, damping=10, bias=True, method='cd', rng_spec=1)  # Use ALS algorithm
    all_recs = []
    valid_data = []

    for train, valid in xf.partition_users(train_data[['user', 'item', 'rating']], 5, xf.SampleFrac(0.2), rng_spec=1):
        valid_data.append(valid)
        all_recs.append(evaluate_with_ndcg('ALS', algo_als, train, valid))  # Use 'ALS' as the algorithm name

    all_recs = pd.concat(all_recs, ignore_index=True)
    valid_data = pd.concat(valid_data, ignore_index=True)

    rla = topn.RecListAnalysis()
    rla.add_metric(topn.ndcg)
    fold_results = rla.compute(all_recs, valid_data)

    # Calculate mean nDCG directly from fold_results
    mean_ndcg = fold_results['ndcg'].mean()
    results.append({'Features': features, 'Mean nDCG': mean_ndcg})

    if mean_ndcg > best_mean_ndcg:
        best_mean_ndcg = mean_ndcg
        best_features = features

# Print results
print("Results:")
for result in results:
    print(f"Features = {result['Features']}: Mean nDCG = {result['Mean nDCG']:.4f}")

print(f"\nBest Number of Features: {best_features} (Mean nDCG = {best_mean_ndcg:.4f})")

# Fit the algorithm on the full training data with the best number of features
algo_als_best = BiasedMF(features=best_features, iterations=10, reg=0.1, damping=10, bias=True, method='cd', rng_spec=1)  # Use ALS algorithm
algo_als_full = Recommender.adapt(util.clone(algo_als_best))
algo_als_full.fit(train_data)

# Get the unique users from the test data
test_users = test_data.user.unique()

# Generate recommendations for the test users with batch processing
test_recs = batch.recommend(algo_als_full, test_users, 10)
test_recs['Algorithm'] = 'ALS'

# Evaluate the recommendations using the test set
test_rla = topn.RecListAnalysis()
test_rla.add_metric(topn.ndcg)
test_results = test_rla.compute(test_recs, test_data)

# Display the evaluation results
print(test_results.head())
print("NDCG mean for test set:", test_results.groupby('Algorithm').ndcg.mean())