# -*- coding: utf-8 -*-
"""Bias_LensKit_ML100K_Automated Fine Tuned_K fold.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VaS6iidmhhUfijbSrNbjBEW9N1taXKYR
"""

!pip install lenskit

from lenskit import batch, topn, util
from lenskit import crossfold as xf
from lenskit.algorithms import Recommender
from lenskit.algorithms.bias import Bias  # Import Bias algorithm
from sklearn.model_selection import train_test_split
import pandas as pd
from lenskit.datasets import ML100K
import seedbank

# Initialize seed
seedbank.initialize(1)

# Function to down-sample the dataset
def downsample_data(ratings, percentage):
    sampled_ratings = ratings.sample(frac=percentage, random_state=1)
    return sampled_ratings

# Load and preprocess the dataset
file_path = '/content/drive/MyDrive/Master Thesis/Dataset/ml-100k'
ml100k = ML100K(file_path)
ratings = ml100k.ratings

# Split into train and test sets
train_data, test_data = train_test_split(ratings, test_size=0.1, random_state=1)

# Down-sample the training data
train_data = downsample_data(train_data, percentage=0.7)

# Function to evaluate with nDCG metric
def evaluate_with_ndcg(aname, algo, train, valid):
    fittable = util.clone(algo)
    fittable = Recommender.adapt(fittable)
    fittable.fit(train)
    users = valid.user.unique()
    recs = batch.recommend(fittable, users, 10)
    recs['Algorithm'] = aname
    return recs

# Hyperparameter tuning for damping values
damping_values = [1, 5, 10, 20, 50, 100]
best_ndcg = 0
best_damping = 0

for damping in damping_values:
    results = []
    all_recs = []
    valid_data = []

    for train, valid in xf.partition_users(train_data[['user', 'item', 'rating']], 5, xf.SampleFrac(0.2), rng_spec=1):
        algo_bias = Bias(damping=damping)
        valid_data.append(valid)
        fold_recs = evaluate_with_ndcg('Bias', algo_bias, train, valid)
        all_recs.append(fold_recs)

    all_recs = pd.concat(all_recs, ignore_index=True)
    valid_data = pd.concat(valid_data, ignore_index=True)

    rla = topn.RecListAnalysis()
    rla.add_metric(topn.ndcg)
    fold_results = rla.compute(all_recs, valid_data)

    mean_ndcg = fold_results['ndcg'].mean()
    results.append({'Algorithm': 'Bias', 'Damping': damping, 'Mean nDCG': mean_ndcg})

    print(f"Damping {damping}: Mean nDCG = {mean_ndcg:.4f}")

    if mean_ndcg > best_ndcg:
        best_ndcg = mean_ndcg
        best_damping = damping

print(f"Best damping value: {best_damping} with mean nDCG: {best_ndcg:.4f}")

# Fit the algorithm on the full training data using the best damping value
algo_bias_full = Bias(damping=best_damping)
algo_bias_full = Recommender.adapt(util.clone(algo_bias_full))
algo_bias_full.fit(train_data)

# Get the unique users from the test data
test_users = test_data.user.unique()

# Generate recommendations for the test users with batch processing
test_recs = batch.recommend(algo_bias_full, test_users, 10)
test_recs['Algorithm'] = 'Bias'

# Evaluate the recommendations using the test set
test_rla = topn.RecListAnalysis()
test_rla.add_metric(topn.ndcg)
test_results = test_rla.compute(test_recs, test_data)

# Display the evaluation results
print(test_results.head())
print("NDCG mean for test set:", test_results.groupby('Algorithm').ndcg.mean())