# -*- coding: utf-8 -*-
"""Plot_Movielens100K_Best perfotmance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztKbZcGcC9QP53fSflFRlJZONw1fz0V-
"""

import pandas as pd
import matplotlib.pyplot as plt

# Example results
data = {
    'Percentage': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    'FunkSVD': [0.0401 ,0.0362, 0.0297, 0.0305, 0.0299, 0.0309, 0.0331, 0.0348, 0.0363, 0.0379],
    'UserKNN': [0.0126, 0.0131, 0.0085, 0.0074, 0.0086, 0.0117, 0.0108, 0.0120, 0.0132, 0.0133],
    'ItemKNN': [0.0175, 0.0135, 0.0133, 0.0139, 0.0154, 0.0125, 0.0142, 0.0149, 0.0216, 0.0220],
    'ALS': [0.0323, 0.0299, 0.0285, 0.0290, 0.0321, 0.0365, 0.0405, 0.0432, 0.0479, 0.0534],
    'Popular': [0.0614, 0.0651, 0.0663, 0.0704, 0.0734, 0.0804, 0.0861, 0.0912, 0.0998, 0.1101],
    'Bias': [0.0465, 0.0424, 0.0466, 0.0455, 0.0447, 0.0504, 0.0544, 0.0575, 0.0620, 0.0637],
    'Random': [0.0073, 0.0061, 0.0057, 0.0057, 0.0067,0.0062, 0.0040, 0.0075, 0.0058, 0.0051]
}

df = pd.DataFrame(data)
print(df)

plt.figure(figsize=(14, 8))
plt.style.use('seaborn-darkgrid')

# Plot each algorithm's nDCG values
for algorithm in df.columns[1:]:
    plt.plot(df['Percentage'], df[algorithm], marker='o', linestyle='-', linewidth=2, label=algorithm)

# Add title and labels
plt.title('Movielens 100K', fontsize=16)
plt.xlabel('Percentage of Dataset Used', fontsize=14)
plt.ylabel('nDCG @ 10 Score', fontsize=14)
plt.xticks(df['Percentage'])
plt.yticks(fontsize=12)

# Add a legend
plt.legend(title='Algorithm', fontsize=12)

# Show the plot
plt.grid(True)
plt.show()