# -*- coding: utf-8 -*-
"""Plot_Movielens1M_Best perfotmance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vjhyj7ipXBwu4RuvnTLB5A_FyC2XVOps
"""

import pandas as pd
import matplotlib.pyplot as plt

# Example results
data = {
    'Percentage': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    'FunkSVD': [0.0334, 0.0268, 0.0289, 0.0290, 0.0298, 0.0283, 0.0278, 0.0300, 0.0288, 0.0290],
    'UserKNN': [0.0063, 0.0041, 0.0034, 0.0034, 0.0043, 0.0050, 0.0056, 0.0073, 0.0092, 0.0102],
    'ItemKNN': [0.0106, 0.0077, 0.0071, 0.0068, 0.0064, 0.0076, 0.0095, 0.0120, 0.0139, 0.0149],
    'ALS':[0.0262, 0.0245, 0.0287, 0.0307, 0.0311, 0.0331, 0.0335, 0.0355, 0.0372, 0.0369],
    'Popular':[0.0467, 0.0503, 0.0527, 0.0550, 0.0586, 0.0628, 0.0676, 0.0734, 0.0804, 0.0896],
    'Bias':[0.0376, 0.0365, 0.0388, 0.0392, 0.0405, 0.0409, 0.0413, 0.0428, 0.0446, 0.0464],
    'Random': [0.0025, 0.0030, 0.0025, 0.0030, 0.0028, 0.0027, 0.0026, 0.0024, 0.0028, 0.0026]
}

df = pd.DataFrame(data)
print(df)

plt.figure(figsize=(14, 8))
plt.style.use('seaborn-darkgrid')

# Plot each algorithm's nDCG values
for algorithm in df.columns[1:]:
    plt.plot(df['Percentage'], df[algorithm], marker='o', linestyle='-', linewidth=2, label=algorithm)

# Add title and labels
plt.title('Movielens 1M', fontsize=16)
plt.xlabel('Percentage of Dataset Used', fontsize=14)
plt.ylabel('nDCG @ 10 Score', fontsize=14)
plt.xticks(df['Percentage'])
plt.yticks(fontsize=12)

# Add a legend
plt.legend(title='Algorithm', fontsize=12)

# Show the plot
plt.grid(True)
plt.show()