# -*- coding: utf-8 -*-
"""NeuMF_RecBole_CDs and Vinyl_UserBasedSplit+10_Core_Pruning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VX_gaUUa5x_qpii7_3FBPL1wTbGc-4g6
"""

!pip install recbole
!pip install kmeans-pytorch
!pip install ray

import pandas as pd
import random
import numpy as np
import joblib
import gzip
import json
import torch
import kmeans_pytorch
import ray
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.quick_start import load_data_and_model, run_recbole
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.model.general_recommender import NeuMF

# Function to load the JSON data
def load_json_data(file_path, chunksize=10000):
    chunks = pd.read_json(file_path, lines=True, compression='gzip', chunksize=chunksize)
    return pd.concat(chunks, ignore_index=True)

# Set random seed for reproducibility
np.random.seed(42)

# Load and preprocess ratings data
file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Amazon/CDs_and_Vinyl_5.json.gz'
ratings = load_json_data(file_path)
print(len(ratings))

# Rename columns to match RecPack expectations
ratings = ratings.rename(columns={'reviewerID': 'user_id', 'asin': 'item_id', 'overall': 'rating'})
ratings = ratings.dropna(subset=['rating'])

# Convert 'rating' column to float
ratings['rating'] = ratings['rating'].astype(float)

# Keep only the necessary columns
ratings = ratings[['user_id', 'item_id', 'rating']]
print(ratings.head())
print(len(ratings))

# Convert user and item IDs to integers
ratings['user_id'], user_index = pd.factorize(ratings['user_id'])
ratings['item_id'], item_index = pd.factorize(ratings['item_id'])
print(ratings.head())
print(len(ratings))

# Inspect the ratings data
print("Initial Ratings Data Inspection:")
print("Number of interactions:", len(ratings))
print("Number of unique users:", ratings['user_id'].nunique())
print("Number of unique items:", ratings['item_id'].nunique())

# Check for users and items with fewer than 10 interactions
user_counts = ratings['user_id'].value_counts()
item_counts = ratings['item_id'].value_counts()

print("\nUsers with fewer than 10 interactions:", (user_counts < 10).sum())
print("Items with fewer than 10 interactions:", (item_counts < 10).sum())

# Check for empty rows
empty_rows = ratings.isnull().sum().sum()
print("\nNumber of empty rows:", empty_rows)

# Check for duplicate rows
duplicate_rows = ratings.duplicated().sum()
print("Number of duplicate rows:", duplicate_rows)

# Check for duplicate ratings (same user, same item)
duplicate_ratings = ratings.duplicated(subset=['user_id', 'item_id']).sum()
print("Number of duplicate ratings (same user, same item):", duplicate_ratings)

# Remove duplicate rows
ratings = ratings.drop_duplicates()

# Aggregate duplicate ratings (same user, same item) by averaging their ratings
ratings = ratings.groupby(['user_id', 'item_id'], as_index=False)['rating'].mean()

# Check for empty rows after cleaning
empty_rows = ratings.isnull().sum().sum()
print("\nNumber of empty rows after cleaning:", empty_rows)

# Check for duplicate rows after cleaning
duplicate_rows = ratings.duplicated().sum()
print("Number of duplicate rows after cleaning:", duplicate_rows)

# Check for duplicate ratings (same user, same item) after cleaning
duplicate_ratings = ratings.duplicated(subset=['user_id', 'item_id']).sum()
print("Number of duplicate ratings (same user, same item) after cleaning:", duplicate_ratings)

print(len(ratings))

# 10-core pruning
def prune_10_core(data):
    while True:
        # Filter users with fewer than 10 interactions
        user_counts = data['user_id'].value_counts()
        valid_users = user_counts[user_counts >= 10].index
        data = data[data['user_id'].isin(valid_users)]

        # Filter items with fewer than 10 interactions
        item_counts = data['item_id'].value_counts()
        valid_items = item_counts[item_counts >= 10].index
        data = data[data['item_id'].isin(valid_items)]

        # Check if no more pruning is needed
        if all(user_counts >= 10) and all(item_counts >= 10):
            break
    return data

# Apply 10-core pruning
ratings = prune_10_core(ratings)
print(len(ratings))
# Downsample to n% of each user's interactions
ratings = ratings.groupby('user_id').sample(frac=1.0, random_state=42)

print("Number of interactions after downsampling:", len(ratings))
# Check the number of unique users and items after downsampling
num_users = ratings['user_id'].nunique()
num_items = ratings['item_id'].nunique()

print("Number of unique users after downsampling:", num_users)
print("Number of unique items after downsampling:", num_items)

# Save the preprocessed dataset as a CSV file
output_file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Amazon/CDs-and-Vinyl-RecBole/preprocessed_ratings.csv'
ratings.to_csv(output_file_path, index=False)

# Set the random seed for all libraries
random_seed = 42
random.seed(random_seed)  # For Python's random module
np.random.seed(random_seed)  # For NumPy
torch.manual_seed(random_seed)  # For PyTorch

# Load the preprocessed ratings file
preprocessed_file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Amazon/CDs-and-Vinyl-RecBole/preprocessed_ratings.csv'
ratings = pd.read_csv(preprocessed_file_path)

# Create atomic files
# Create the interaction file
interaction_file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Amazon/CDs-and-Vinyl-RecBole/CDs-and-Vinyl-RecBole.inter'
with open(interaction_file_path, 'w') as f:
    # Write the header
    f.write("user_id:token\titem_id:token\trating:float\n")

    # Write the interaction data
    for index, row in ratings.iterrows():
        user_id = int(row['user_id'])  # Ensure user_id is an integer
        item_id = int(row['item_id'])  # Ensure item_id is an integer
        rating = row['rating']          # Rating can remain as float
        f.write(f"{user_id}\t{item_id}\t{rating}\n")  # Write the row with tab separation

# User file
user_data = pd.DataFrame({
    'user_id': ratings['user_id'].unique()
})

user_file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Amazon/CDs-and-Vinyl-RecBole/CDs-and-Vinyl-RecBole.user'
with open(user_file_path, 'w') as f:
    f.write("user_id:token\n")
    for user_id in user_data['user_id']:
        f.write(f"{user_id}\n")

# Item file
item_data = pd.DataFrame({
    'item_id': ratings['item_id'].unique()
})

item_file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Amazon/CDs-and-Vinyl-RecBole/CDs-and-Vinyl-RecBole.item'
with open(item_file_path, 'w') as f:
    f.write("item_id:token\n")
    for item_id in item_data['item_id']:
        f.write(f"{item_id}\n")

yaml_content = """
# CDs-and-Vinyl-RecBole.yaml

# Dataset configuration
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating

load_col:
    inter: [user_id, item_id, rating]  # Include timestamp if applicable

# Data path configuration
data_path: '/content/drive/MyDrive/Master Thesis/Dataset/Amazon/'  # Parent dir of atomic files
dataset: CDs-and-Vinyl-RecBole  # Name of the dataset

# Model configuration
embedding_size: 64

# Training and evaluation configuration
epochs: 50
train_batch_size: 4096
eval_batch_size: 4096
train_neg_sample_args:
    distribution: uniform
    sample_num: 1
    alpha: 1.0
    dynamic: False
    candidate_num: 0
eval_args:
    group_by: user
    order: RO                 # for each downsampling portion, the following combination of ratios is chosen to align with the desired general split setup of the project (10% of total interactions for Validation set, 10% of total interactions for Test set)
    split: {'RS': [8, 1, 1]}  # 28: .28, .36, .36/ 36:.44, .28, .28/ 44:.54, .23, .23/ 52:.62, .19, .19/ 60:.66, .17, .17/ 68:.70, .15, .15/ 76:.74, .13, .13/ 84: .76, .12, .12/ 92: .78, .11, .11/ 100: .8, .1, .1
    mode: full
metrics: ['NDCG']
topk: 10
valid_metric: NDCG@10  # Use nDCG@10 as the valid metric
metric_decimal_place: 4
"""

# Write the content to a file
with open('/content/drive/MyDrive/Master Thesis/Dataset/Amazon/CDs-and-Vinyl-RecBole/CDs-and-Vinyl-RecBole.yaml', 'w') as f:
    f.write(yaml_content)

config = Config(model='NeuMF', dataset='CDs-and-Vinyl-RecBole', config_file_list=['/content/drive/MyDrive/Master Thesis/Dataset/Amazon/CDs-and-Vinyl-RecBole/CDs-and-Vinyl-RecBole.yaml'])
dataset = create_dataset(config)
# Run the LightGCN model
run_recbole(model='NeuMF', dataset='CDs-and-Vinyl-RecBole', config_file_list=['/content/drive/MyDrive/Master Thesis/Dataset/Amazon/CDs-and-Vinyl-RecBole/CDs-and-Vinyl-RecBole.yaml'])

# Step 2: Load the dataset and data splits directly
config = Config(model='NeuMF', dataset='CDs-and-Vinyl-RecBole', config_file_list=['/content/drive/MyDrive/Master Thesis/Dataset/Amazon/CDs-and-Vinyl-RecBole/CDs-and-Vinyl-RecBole.yaml'])
dataset = create_dataset(config)
train_data, valid_data, test_data = data_preparation(config, dataset)

# Function to print dataset statistics
def print_dataset_stats(dataset, train_data, valid_data, test_data):
    # Total users and items in the dataset
    num_users = dataset.user_num
    num_items = dataset.item_num

    # Number of interactions in each split
    num_train_interactions = len(train_data.dataset)
    num_valid_interactions = len(valid_data.dataset)
    num_test_interactions = len(test_data.dataset)

    # Print statistics
    print("Dataset Statistics:")
    print(f"Total Users: {num_users}")
    print(f"Total Items: {num_items}")
    print(f"Training Interactions: {num_train_interactions}")
    print(f"Validation Interactions: {num_valid_interactions}")
    print(f"Test Interactions: {num_test_interactions}")

# Display dataset statistics
print_dataset_stats(dataset, train_data, valid_data, test_data)