# -*- coding: utf-8 -*-
"""NeuMF_RecBole_Gowalla_UserBasedSplit+10_Core_Pruning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouY23B0AMX-YRduaNS2tz_uypAptk3lD
"""

!pip install recbole
!pip install kmeans-pytorch
!pip install ray

import pandas as pd
import random
import numpy as np
import joblib
import gzip
import json
import torch
import kmeans_pytorch
import ray
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.quick_start import load_data_and_model, run_recbole
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.model.general_recommender import NeuMF

# Set the random seed for all libraries
random_seed = 42
random.seed(random_seed)  # For Python's random module
np.random.seed(random_seed)  # For NumPy
torch.manual_seed(random_seed)  # For PyTorch

# Function to load the Gowalla check-in data
def load_gowalla_data(file_path):
    # Specify the columns: user, check-in time, latitude, longitude, location id
    column_names = ['user', 'check_in_time', 'latitude', 'longitude', 'location id']
    # Load the txt file into a pandas DataFrame
    with gzip.open(file_path, 'rt') as f:
        gowalla_data = pd.read_csv(f, sep='\t', names=column_names)
    return gowalla_data

# Load the Gowalla data
file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Gowalla/loc-gowalla_totalCheckins.txt.gz'
ratings = load_gowalla_data(file_path)
print(f"Number of records loaded: {len(ratings)}")

# Rename columns to match RecPack expectations
ratings = ratings.rename(columns={'user': 'user_id', 'location id': 'item_id'})

# Keep only the necessary columns: user_id and item_id
ratings = ratings[['user_id', 'item_id']]
print(ratings.head())
print(len(ratings))

# Inspect the ratings data
print("Initial Ratings Data Inspection:")
print("Number of interactions:", len(ratings))
print("Number of unique users:", ratings['user_id'].nunique())
print("Number of unique items:", ratings['item_id'].nunique())

# Check for users and items with fewer than 10 interactions
user_counts = ratings['user_id'].value_counts()
item_counts = ratings['item_id'].value_counts()

print("\nUsers with fewer than 10 interactions:", (user_counts < 10).sum())
print("Items with fewer than 10 interactions:", (item_counts < 10).sum())

# Check for empty rows
empty_rows = ratings.isnull().sum().sum()
print("\nNumber of empty rows:", empty_rows)

# Check for duplicate rows
duplicate_rows = ratings.duplicated().sum()
print("Number of duplicate rows:", duplicate_rows)

# Remove duplicate rows
ratings = ratings.drop_duplicates()

# Check for empty rows after cleaning
empty_rows = ratings.isnull().sum().sum()
print("\nNumber of empty rows after cleaning:", empty_rows)

# Check for duplicate rows after cleaning
duplicate_rows = ratings.duplicated().sum()
print("Number of duplicate rows after cleaning:", duplicate_rows)

# Check for duplicate ratings (same user, same item) after cleaning
duplicate_ratings = ratings.duplicated(subset=['user_id', 'item_id']).sum()
print("Number of duplicate ratings (same user, same item) after cleaning:", duplicate_ratings)



# 10-core pruning
def prune_10_core(data):
    while True:
        # Filter users with fewer than 10 interactions
        user_counts = data['user_id'].value_counts()
        valid_users = user_counts[user_counts >= 10].index
        data = data[data['user_id'].isin(valid_users)]

        # Filter items with fewer than 10 interactions
        item_counts = data['item_id'].value_counts()
        valid_items = item_counts[item_counts >= 10].index
        data = data[data['item_id'].isin(valid_items)]

        # Check if no more pruning is needed
        if all(user_counts >= 10) and all(item_counts >= 10):
            break
    return data

# Apply 10-core pruning
ratings = prune_10_core(ratings)

# Inspect the pruned ratings data
print("\nAfter Pruning:")
print("Number of interactions:", len(ratings))
print("Number of unique users:", ratings['user_id'].nunique())
print("Number of unique items:", ratings['item_id'].nunique())

# Check for users and items with fewer than 10 interactions after pruning
user_counts = ratings['user_id'].value_counts()
item_counts = ratings['item_id'].value_counts()

print("\nUsers with fewer than 10 interactions after pruning:", (user_counts < 10).sum())
print("Items with fewer than 10 interactions after pruning:", (item_counts < 10).sum())

# Downsample to n% of each user's interactions
ratings = ratings.groupby('user_id').sample(frac=0.28, random_state=42)

print("Number of interactions after downsampling:", len(ratings))
# Check the number of unique users and items after downsampling
num_users = ratings['user_id'].nunique()
num_items = ratings['item_id'].nunique()

print("Number of unique users after downsampling:", num_users)
print("Number of unique items after downsampling:", num_items)
# Save the preprocessed dataset as a CSV file
output_file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Gowalla/Gowalla-RecBole/preprocessed_ratings.csv'
ratings.to_csv(output_file_path, index=False)

# Load the preprocessed interactions file for Gowalla (assuming it has 'user_id' and 'item_id' columns)
preprocessed_file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Gowalla/Gowalla-RecBole/preprocessed_ratings.csv'
interactions = pd.read_csv(preprocessed_file_path)

# Create atomic files without the 'rating' field
# Interaction file
interaction_file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Gowalla/Gowalla-RecBole/Gowalla-RecBole.inter'
with open(interaction_file_path, 'w') as f:
    f.write("user_id:token\titem_id:token\n")  # Only user_id and item_id

    for index, row in interactions.iterrows():
        user_id = int(row['user_id'])
        item_id = int(row['item_id'])
        f.write(f"{user_id}\t{item_id}\n")

# User and item files (remain the same)
user_data = pd.DataFrame({'user_id': interactions['user_id'].unique()})
user_file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Gowalla/Gowalla-RecBole/Gowalla-RecBole.user'
with open(user_file_path, 'w') as f:
    f.write("user_id:token\n")
    for user_id in user_data['user_id']:
        f.write(f"{user_id}\n")

item_data = pd.DataFrame({'item_id': interactions['item_id'].unique()})
item_file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Gowalla/Gowalla-RecBole/Gowalla-RecBole.item'
with open(item_file_path, 'w') as f:
    f.write("item_id:token\n")
    for item_id in item_data['item_id']:
        f.write(f"{item_id}\n")

# Update YAML configuration (exclude RATING_FIELD and rating in load_col)
yaml_content = """
# Gowalla-RecBole.yaml

# Dataset configuration
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id

load_col:
    inter: [user_id, item_id]  # No rating field here

# Data path configuration
data_path: '/content/drive/MyDrive/Master Thesis/Dataset/Gowalla/'  # Parent directory of atomic files
dataset: Gowalla-RecBole  # Name of the dataset

# Model configuration
embedding_size: 64

# Training and evaluation configuration
epochs: 50
train_batch_size: 4096
eval_batch_size: 4096
train_neg_sample_args:
    distribution: uniform
    sample_num: 1
    alpha: 1.0
    dynamic: False
    candidate_num: 0
eval_args:
    group_by: user
    order: RO                      # for each downsampling portion, the following combination of ratios is chosen to align with the desired general split setup of the project (10% of total interactions for Validation set, 10% of total interactions for Test set)
    split: {'RS': [.80, .10, .10]} # 28: .28, .36, .36/ 36:.44, .28, .28/ 44:.54, .23, .23/ 52:.62, .19, .19/ 60:.66, .17, .17/ 68:.70, .15, .15/ 76:.74, .13, .13/ 84: .76, .12, .12/ 92: .78, .11, .11/ 100: .8, .1, .1
    mode: full
metrics: ['NDCG']
topk: 10
valid_metric: NDCG@10
metric_decimal_place: 4
"""

# Write YAML configuration to file
with open('/content/drive/MyDrive/Master Thesis/Dataset/Gowalla/Gowalla-RecBole/Gowalla-RecBole.yaml', 'w') as f:
    f.write(yaml_content)

config = Config(model='NeuMF', dataset='Gowalla-RecBole', config_file_list=['/content/drive/MyDrive/Master Thesis/Dataset/Gowalla/Gowalla-RecBole/Gowalla-RecBole.yaml'])
dataset = create_dataset(config)

# Run the LightGCN model
run_recbole(model='NeuMF', dataset='Gowalla-RecBole', config_file_list=['/content/drive/MyDrive/Master Thesis/Dataset/Gowalla/Gowalla-RecBole/Gowalla-RecBole.yaml'])

config = Config(model='NeuMF', dataset='Gowalla-RecBole', config_file_list=['/content/drive/MyDrive/Master Thesis/Dataset/Gowalla/Gowalla-RecBole/Gowalla-RecBole.yaml'])
dataset = create_dataset(config)
# Run the LightGCN model
run_recbole(model='NeuMF', dataset='Gowalla-RecBole', config_file_list=['/content/drive/MyDrive/Master Thesis/Dataset/Gowalla/Gowalla-RecBole/Gowalla-RecBole.yaml'])

# Step 2: Load the dataset and data splits directly
config = Config(model='NeuMF', dataset='Gowalla-RecBole', config_file_list=['/content/drive/MyDrive/Master Thesis/Dataset/Gowalla/Gowalla-RecBole/Gowalla-RecBole.yaml'])
dataset = create_dataset(config)
train_data, valid_data, test_data = data_preparation(config, dataset)

# Function to print dataset statistics
def print_dataset_stats(dataset, train_data, valid_data, test_data):
    # Total users and items in the dataset
    num_users = dataset.user_num
    num_items = dataset.item_num

    # Number of interactions in each split
    num_train_interactions = len(train_data.dataset)
    num_valid_interactions = len(valid_data.dataset)
    num_test_interactions = len(test_data.dataset)

    # Print statistics
    print("Dataset Statistics:")
    print(f"Total Users: {num_users}")
    print(f"Total Items: {num_items}")
    print(f"Training Interactions: {num_train_interactions}")
    print(f"Validation Interactions: {num_valid_interactions}")
    print(f"Test Interactions: {num_test_interactions}")

# Display dataset statistics
print_dataset_stats(dataset, train_data, valid_data, test_data)