# -*- coding: utf-8 -*-
"""ItemKNN_RecPack_Amazon_Electronics_UserSubset+UserBasedSplit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CfP5mpkXoIZkBrsIqnBGEirmOQLNhc4n
"""

# Install necessary libraries
!pip install recpack

import recpack.pipelines as pipelines
from recpack.scenarios import WeakGeneralization
from recpack.preprocessing.filters import MinItemsPerUser, MinUsersPerItem, Deduplicate
import numpy as np
import pandas as pd
import joblib
import gzip
import json
from recpack.preprocessing.preprocessors import DataFramePreprocessor
import time

start_time = time.time()

# Function to load the JSON data
def load_json_data(file_path, chunksize=10000):
    chunks = pd.read_json(file_path, lines=True, compression='gzip', chunksize=chunksize)
    return pd.concat(chunks, ignore_index=True)
# Set random seed for reproducibility
np.random.seed(42)
# Load and preprocess ratings data
file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Amazon/Electronics_5.json.gz'
ratings = load_json_data(file_path)
print(len(ratings))

# Rename columns to match RecPack expectations
ratings = ratings.rename(columns={'reviewerID': 'user_id', 'asin': 'item_id', 'overall': 'rating'})
ratings = ratings.dropna(subset=['rating'])

# Convert 'rating' column to float
ratings['rating'] = ratings['rating'].astype(float)
# Keep only the necessary columns
ratings = ratings[['user_id', 'item_id', 'rating']]
print(ratings.head())
print(len(ratings))

# Convert user and item IDs to integers
ratings['user_id'], user_index = pd.factorize(ratings['user_id'])
ratings['item_id'], item_index = pd.factorize(ratings['item_id'])
print(ratings.head())
print(len(ratings))

# Inspect the ratings data
print("Initial Ratings Data Inspection:")
print("Number of interactions:", len(ratings))
print("Number of unique users:", ratings['user_id'].nunique())
print("Number of unique items:", ratings['item_id'].nunique())

# Check for users and items with fewer than 10 interactions
user_counts = ratings['user_id'].value_counts()
item_counts = ratings['item_id'].value_counts()

print("\nUsers with fewer than 10 interactions:", (user_counts < 10).sum())
print("Items with fewer than 10 interactions:", (item_counts < 10).sum())

# Check for empty rows
empty_rows = ratings.isnull().sum().sum()
print("\nNumber of empty rows:", empty_rows)

# Check for duplicate rows
duplicate_rows = ratings.duplicated().sum()
print("Number of duplicate rows:", duplicate_rows)
# Check for duplicate ratings (same user, same item)
duplicate_ratings = ratings.duplicated(subset=['user_id', 'item_id']).sum()
print("Number of duplicate ratings (same user, same item):", duplicate_ratings)

# Remove duplicate rows
ratings = ratings.drop_duplicates()
# Aggregate duplicate ratings (same user, same item) by averaging their ratings
ratings = ratings.groupby(['user_id', 'item_id'], as_index=False)['rating'].mean()

# Check for empty rows after cleaning
empty_rows = ratings.isnull().sum().sum()
print("\nNumber of empty rows after cleaning:", empty_rows)

# Check for duplicate rows after cleaning
duplicate_rows = ratings.duplicated().sum()
print("Number of duplicate rows after cleaning:", duplicate_rows)

# Check for duplicate ratings (same user, same item) after cleaning
duplicate_ratings = ratings.duplicated(subset=['user_id', 'item_id']).sum()
print("Number of duplicate ratings (same user, same item) after cleaning:", duplicate_ratings)

# 10-core pruning
def prune_10_core(data):
    while True:
        # Filter users with fewer than 10 interactions
        user_counts = data['user_id'].value_counts()
        valid_users = user_counts[user_counts >= 10].index
        data = data[data['user_id'].isin(valid_users)]

        # Filter items with fewer than 10 interactions
        item_counts = data['item_id'].value_counts()
        valid_items = item_counts[item_counts >= 10].index
        data = data[data['item_id'].isin(valid_items)]

        # Check if no more pruning is needed
        if all(user_counts >= 10) and all(item_counts >= 10):
            break
    return data
# Apply 10-core pruning
ratings = prune_10_core(ratings)
print(len(ratings))

# Inspect the ratings data
print("Initial Ratings Data Inspection:")
print("Number of interactions:", len(ratings))
print("Number of unique users:", ratings['user_id'].nunique())
print("Number of unique items:", ratings['item_id'].nunique())

# 10% validation + 10% test set + n% of the training set based on the desired downsampling portion----> 0.28      0.36        0.44      0.52      0.60      0.68     0.76     0.84      0.92      1.0

import random

def downsample_ratings(ratings, target_percentage= 0.84):
    # Calculate total number of interactions and target interactions (n% of the total)
    total_interactions = len(ratings)
    target_interactions = total_interactions * target_percentage
    print(f"Total interactions: {total_interactions}, Target interactions: {int(target_interactions)}")

    # Shuffle the users randomly
    users = ratings['user_id'].unique()
    random.shuffle(users)

    # Initialize variables for tracking selected users and interactions
    selected_users = []
    selected_interactions = 0

    # Loop through the shuffled users, summing their interactions
    for user in users:
        user_interactions = ratings[ratings['user_id'] == user]
        user_interaction_count = len(user_interactions)

        # Add the user to the selected users and update the interaction count
        selected_users.append(user)
        selected_interactions += user_interaction_count

        # Stop once we exceed the target number of interactions
        if selected_interactions >= target_interactions:
            break

    # Create the new downsampled dataset with the selected users
    downsampled_ratings = ratings[ratings['user_id'].isin(selected_users)]

    print(f"Selected {len(selected_users)} users with {selected_interactions} interactions.")
    return downsampled_ratings

# Apply the downsampling function
downsampled_ratings = downsample_ratings(ratings)
print(downsampled_ratings.head())

# Preprocess the data using RecPack
proc = DataFramePreprocessor(item_ix='item_id', user_ix='user_id')
# Process the DataFrame to get the interaction matrix
interaction_matrix = proc.process(downsampled_ratings)

# Check and remove empty rows (users with no interactions) and empty columns (items with no interactions)
# This should not change anything due to the 10-core filtering already applied
interaction_matrix = interaction_matrix.users_in(interaction_matrix.active_users)
interaction_matrix = interaction_matrix.items_in(interaction_matrix.active_items)

# Print the number of interactions, users, and items after ensuring no empty rows or columns
print("Number of interactions after ensuring no empty rows or columns:", interaction_matrix.num_interactions)
print("Number of unique users after ensuring no empty rows or columns:", len(interaction_matrix.active_users))
print("Number of unique items after ensuring no empty rows or columns:", len(interaction_matrix.active_items))

# Define the WeakGeneralization scenario with 20% of the data for testing+validation (The fraction value is slightly different since due to the fact that the splitting procedure rounds up the values,
# therefore the split ratio won't be exactly 80-20 anymore, so I adjusted the split ratio manually to make sure the 80-20 ratio is correctly maintained)
# 28%----> 0.74      36%----> 0.585     44%-----> 0.49     52%----> 0.415     60%----> 0.365     68%----> 0.32      76%----> 0.295       84%----> 0.27       92%----> 0.249         100%----> 0.229
test_valid_fraction = 0.27
weak_gen_scenario = WeakGeneralization(frac_data_in=1 - test_valid_fraction, validation=False, seed=42)

# Split the data
weak_gen_scenario.split(interaction_matrix)

# Use attributes to get the train+validation and test sets
train_interactions = weak_gen_scenario.full_training_data
test_valid_interactions = weak_gen_scenario.test_data_out

print("Number of interactions in train set:", train_interactions.num_interactions)
print("Number of interactions in test_valid set:", test_valid_interactions.num_interactions)

# Splitting test_valid set from each other (Again, fraction value is slightly different to maintatin the 50-50 split ration in this case correctly (due to rounding up effect))
# 28%----> 0.455     36%----> 0.44    44%-----> 0.43         52%----> 0.43    60%----> 0.41    68%---> 0.37     76%---> 0.39      84%----> 0.39        92%----> 0.38       100%---> 0.40
test_valid_scenario = WeakGeneralization(frac_data_in=0.39, validation=False, seed=42)

# Split the data
test_valid_scenario.split(test_valid_interactions)

# Use attributes to get the train+validation and test sets
valid_interactions = test_valid_scenario.full_training_data
test_out_interactions = test_valid_scenario.test_data_out
print("Number of interactions in valid set:", valid_interactions.num_interactions)
print("Number of interactions in test set:", test_out_interactions.num_interactions)
print("Number of unique users in validation set:", len(valid_interactions.active_users))
print("Number of unique items in validation set:", len(valid_interactions.active_items))
print("Number of unique users in test set:", len(test_out_interactions.active_users))
print("Number of unique items in test set:", len(test_out_interactions.active_items))
print("Number of unique users in training set:", len(train_interactions.active_users))

# Construct pipeline_builder and add data
pipeline_builder = pipelines.PipelineBuilder('Amazon_Electronics')


pipeline_builder.set_full_training_data(train_interactions)
pipeline_builder.set_test_data((train_interactions, test_out_interactions))
pipeline_builder.set_validation_training_data(train_interactions)
pipeline_builder.set_validation_data((train_interactions, valid_interactions))

# Add ItemKNN algorithm with hyperparameter ranges for optimization
pipeline_builder.add_algorithm(
    'ItemKNN',
    grid={
        'K': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 150, 200],  # Range of K values for optimization
    }
)

# Set NDCGK as the optimization metric to evaluate at K=10
pipeline_builder.set_optimisation_metric('NDCGK', K=10)

# Add NDCGK metric to be evaluated at K=10
pipeline_builder.add_metric('NDCGK', [10])

# Construct pipeline
pipeline = pipeline_builder.build()

# Run pipeline, will first do optimisation, and then evaluation
pipeline.run()

# Get the metric results
metric_results = pipeline.get_metrics()

# Print the metric results
print("Metric Results:")
print(metric_results)

# Print the best hyperparameters
print("Best Hyperparameters:")
print(pipeline.optimisation_results)

end_time = time.time()

# Calculate the total runtime in seconds
total_time = end_time - start_time

# Convert the total runtime into minutes and seconds
minutes = total_time // 60
seconds = total_time % 60

print(f"Total runtime: {int(minutes)} minutes and {int(seconds)} seconds")
