# -*- coding: utf-8 -*-
"""itemKNN_LensKit_ML100K.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYL8A-KOE5QoTUuszk7wUGvT0gXV5lDb
"""

!pip install lenskit

from lenskit.datasets import ML100K
from lenskit.algorithms import Recommender, item_knn as knn
from lenskit import batch, topn, util
#from lenskit.crossfold import partition_users
from sklearn.model_selection import train_test_split
import pandas as pd
import joblib

# Function to down-sample the dataset
def downsample_data(ratings, percentage):
    # Assuming ratings is a DataFrame with columns ['user', 'item', 'rating']
    sampled_ratings = ratings.sample(frac=percentage, random_state=1)
    return sampled_ratings

# Load the dataset
ml100k = ML100K('/content/drive/MyDrive/Master Thesis/Dataset/ml-100k')
ratings = ml100k.ratings

# Down-sample the dataset to 10% (adjust percentage as needed)
ratings = downsample_data(ratings, percentage=0.1)

# Split data into training, validation, and test sets (60%, 20%, 20%)
train_data, remaining_data = train_test_split(ratings, test_size=0.4, random_state=1)
valid_data, test_data = train_test_split(remaining_data, test_size=0.5, random_state=1)

# Initialize ItemItem recommender algorithm
algo_ii = knn.ItemItem(20)

# Function to evaluate the algorithm
def evaluate_algorithm(algo, train, valid):
    fittable = util.clone(algo)
    fittable = Recommender.adapt(fittable)
    fittable.fit(train)

    users = valid.user.unique()
    recs = batch.recommend(fittable, users, 100)
    recs['Algorithm'] = 'ItemItem'

    # Compute nDCG on validation set
    rla = topn.RecListAnalysis()
    rla.add_metric(topn.ndcg)
    results = rla.compute(recs, valid)
    nDCG_mean = results.groupby('Algorithm').ndcg.mean().iloc[0]
     # Save the model with a unique name
    joblib.dump(fittable, 'itemitem_model.pkl')
    return nDCG_mean

nDCG_validation = evaluate_algorithm(algo_ii, train_data, valid_data)
print(f"Validation nDCG for ItemItem: {nDCG_validation}")

# Function to load the model and evaluate on test set
def evaluate_on_test_set(test):
    # Load the model
    loaded_model = joblib.load('itemitem_model.pkl')

    # Evaluate on test set
    test_users = test.user.unique()
    test_recs = batch.recommend(loaded_model, test_users, 100)
    test_recs['Algorithm'] = 'ItemItem'

    # Compute nDCG on test set
    rla = topn.RecListAnalysis()
    rla.add_metric(topn.ndcg)
    test_results = rla.compute(test_recs, test)
    test_nDCG_mean = test_results.groupby('Algorithm').ndcg.mean().iloc[0]

    return test_nDCG_mean

# Evaluate on test set whenever needed
# nDCG_test = evaluate_on_test_set(test_data)
# print(f"Test nDCG for ItemItem: {nDCG_test}")