# -*- coding: utf-8 -*-
"""Plot_ML1M.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FpAEGIzqEAgQoICmU4FB4CCbsuGZxy-Y
"""

import pandas as pd
import matplotlib.pyplot as plt

# Example results
data = {
    'Percentage': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    'FunkSVD': [0.0023, 0.0028, 0.0036, 0.0046,0.0034,0.0038,0.0040,0.0043,0.0048,0.0049],
    'UserKNN': [0.0071,0.0063,0.0081,0.0092,0.0108,0.0116,0.0128,0.0133,0.0140,0.0149],
    'ItemKNN': [0.0036,0.0046,0.0046,0.0065,0.0069,0.0076,0.0083,0.0089,0.0095,0.0099],
    'ALS':[0.0392,0.0428,0.0457,0.0525,0.0414,0.0439,0.0479,0.0510,0.0567,0.0601]
}

df = pd.DataFrame(data)
print(df)

plt.figure(figsize=(14, 8))
plt.style.use('seaborn-darkgrid')

# Plot each algorithm's nDCG values
for algorithm in df.columns[1:]:
    plt.plot(df['Percentage'], df[algorithm], marker='o', linestyle='-', linewidth=2, label=algorithm)

# Add title and labels
plt.title('Movielens 100K', fontsize=16)
plt.xlabel('Percentage of Dataset Used', fontsize=14)
plt.ylabel('nDCG Score', fontsize=14)
plt.xticks(df['Percentage'])
plt.yticks(fontsize=12)

# Add a legend
plt.legend(title='Algorithm', fontsize=12)

# Show the plot
plt.grid(True)
plt.show()