# -*- coding: utf-8 -*-
"""Plot_Movielens100K.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_XehwVXqUq-2ypLeFTVyVKncCOy6Vf7
"""

import pandas as pd
import matplotlib.pyplot as plt

# Example results
data = {
    'Percentage': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    'FunkSVD': [0.0138, 0.0194, 0.0216, 0.0249, 0.0313, 0.0363, 0.0389, 0.0434, 0.0449, 0.0520],
    'UserKNN': [0.0336, 0.0274, 0.0243, 0.0291, 0.0293, 0.0327, 0.0419, 0.0414, 0.0496, 0.0516],
    'ItemKNN': [0.0087,0.0071,0.0045,0.0059,0.0078,0.0077,0.0086,0.0133,0.0119,0.0168],
    'ALS':[0.0493,0.0568,0.0699,0.0734,0.0838,0.0885,0.0949,0.1010,0.1105,0.1175]
}

df = pd.DataFrame(data)
print(df)

plt.figure(figsize=(14, 8))
plt.style.use('seaborn-darkgrid')

# Plot each algorithm's nDCG values
for algorithm in df.columns[1:]:
    plt.plot(df['Percentage'], df[algorithm], marker='o', linestyle='-', linewidth=2, label=algorithm)

# Add title and labels
plt.title('Movielens 100K', fontsize=16)
plt.xlabel('Percentage of Dataset Used', fontsize=14)
plt.ylabel('nDCG Score', fontsize=14)
plt.xticks(df['Percentage'])
plt.yticks(fontsize=12)

# Add a legend
plt.legend(title='Algorithm', fontsize=12)

# Show the plot
plt.grid(True)
plt.show()