# -*- coding: utf-8 -*-
"""Plot_Toys and Games_Best performane.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wsXc3x9RJerUcm9NSFGhhsk4vlLs8w6h
"""

import pandas as pd
import matplotlib.pyplot as plt

# Example results
data = {
    'Percentage': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    'FunkSVD': [0.0017, 0.0009, 0.0008, 0.0008, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0003],
    'UserKNN': [0.0004, 0.0013, 0.0015, 0.0018, 0.0017, 0.0022, 0.0023, 0.0028, 0.0031, 0.0031],
    'ItemKNN': [0.0054, 0.0055, 0.0051, 0.0045, 0.0036, 0.0031, 0.0026, 0.0020, 0.0019, 0.0015],
    'ALS':[0.0017, 0.0016, 0.0019, 0.0018, 0.0017, 0.0016, 0.0020, 0.0019, 0.0018, 0.0019],
    'Popular':[0.0048, 0.0057, 0.0052, 0.0048, 0.0045, 0.0042, 0.0039, 0.0034, 0.0031, 0.0027],
    'Bias':[0.0040, 0.0036, 0.0033, 0.0032, 0.0032, 0.0031, 0.0029, 0.0022, 0.0021, 0.0020],
    'Random': [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001 ]
}

df = pd.DataFrame(data)
print(df)

plt.figure(figsize=(14, 8))
plt.style.use('seaborn-darkgrid')

# Plot each algorithm's nDCG values
for algorithm in df.columns[1:]:
    plt.plot(df['Percentage'], df[algorithm], marker='o', linestyle='-', linewidth=2, label=algorithm)

# Add title and labels
plt.title('Amazon Toys and Games (1.75M Ratings)', fontsize=16)
plt.xlabel('Percentage of Dataset Used', fontsize=14)
plt.ylabel('nDCG @ 10 Score', fontsize=14)
plt.xticks(df['Percentage'])
plt.yticks(fontsize=12)

# Add a legend
plt.legend(title='Algorithm', fontsize=12)

# Show the plot
plt.grid(True)
plt.show()