# -*- coding: utf-8 -*-
"""UserKNN_LensKit_Toys and Games_Automated Fine tuned+K fold.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gauqC8nNWbUj6nibdQgx2gT3ZM1kenic
"""

!pip install lenskit

from lenskit.algorithms import Recommender, user_knn as knn
from lenskit import batch, topn, util
from sklearn.model_selection import train_test_split
import pandas as pd
import joblib
import gzip
import json
from lenskit import crossfold as xf
import seedbank

seedbank.initialize(1)

# Function to load the JSON data
def load_json_data(file_path, chunksize=10000):
    chunks = pd.read_json(file_path, lines=True, compression='gzip', chunksize=chunksize)
    return pd.concat(chunks, ignore_index=True)

# Function to down-sample the dataset
def downsample_data(ratings, percentage):
    sampled_ratings = ratings.sample(frac=percentage, random_state=1)
    return sampled_ratings
# Function to filter low interaction users and items
def filter_low_interaction(ratings, min_user_interactions=5, min_item_interactions=5):
    user_counts = ratings['user'].value_counts()
    item_counts = ratings['item'].value_counts()
    filtered_ratings = ratings[ratings['user'].isin(user_counts[user_counts >= min_user_interactions].index) &
                               ratings['item'].isin(item_counts[item_counts >= min_item_interactions].index)]
    return filtered_ratings


# Load and preprocess ratings data
file_path = '/content/drive/MyDrive/Master Thesis/Dataset/Amazon/Toys_and_Games_5.json.gz'
ratings = load_json_data(file_path)
ratings = ratings.rename(columns={'reviewerID': 'user', 'asin': 'item', 'overall': 'rating'})
ratings = ratings.dropna(subset=['rating'])
# Convert 'rating' column to float
ratings['rating'] = ratings['rating'].astype(float)
# Keep only the necessary columns
ratings = ratings[['user', 'item', 'rating']]
print(ratings.head())

# Handle duplicate ratings by averaging them
ratings = ratings.groupby(['user', 'item']).agg({'rating': 'mean'}).reset_index()
print(ratings.head())

# Convert user and item IDs to integers
ratings['user'], user_index = pd.factorize(ratings['user'])
ratings['item'], item_index = pd.factorize(ratings['item'])
print(ratings.head())
print(len(ratings))

# Filter users and items with low interactions
ratings = filter_low_interaction(ratings, min_user_interactions=5, min_item_interactions=5)

import matplotlib.pyplot as plt

# Plot the distribution of ratings
ratings['rating'].hist(bins=20)
plt.xlabel('Rating')
plt.ylabel('Count')
plt.title('Distribution of Ratings Amazon_Toys and Games')
plt.show()

# Split into train and test sets
train_data, test_data = train_test_split(ratings, test_size=0.1, random_state=1)

# Down-sample the training data
train_data = downsample_data(train_data, percentage=0.1)

# Function to evaluate with nDCG metric
def evaluate_with_ndcg(aname, algo, train, valid):
    fittable = util.clone(algo)
    fittable = Recommender.adapt(fittable)
    fittable.fit(train)
    users = valid.user.unique()
    recs = batch.recommend(fittable, users, 10)
    recs['Algorithm'] = aname
    return recs

# Perform k-fold cross-validation for different values of K and compute nDCG
results = []
best_k = None
best_mean_ndcg = -float('inf')

for k in [1, 2, 3, 10]:  # Iterate over K values from 1 to 20
    seedbank.initialize(1)
    algo_uu = knn.UserUser(k)  # Use UserUser instead of ItemItem
    all_recs = []
    valid_data = []

    for train, valid in xf.partition_users(train_data[['user', 'item', 'rating']], 5, xf.SampleFrac(0.2), rng_spec=1):
        valid_data.append(valid)
        all_recs.append(evaluate_with_ndcg('UserUser', algo_uu, train, valid))  # Use 'UserUser' as the algorithm name

    all_recs = pd.concat(all_recs, ignore_index=True)
    valid_data = pd.concat(valid_data, ignore_index=True)

    rla = topn.RecListAnalysis()
    rla.add_metric(topn.ndcg)
    fold_results = rla.compute(all_recs, valid_data)

    # Calculate mean nDCG directly from fold_results
    mean_ndcg = fold_results['ndcg'].mean()
    results.append({'K': k, 'Mean nDCG': mean_ndcg})

    if mean_ndcg > best_mean_ndcg:
        best_mean_ndcg = mean_ndcg
        best_k = k

# Print results
print("Results:")
for result in results:
    print(f"K = {result['K']}: Mean nDCG = {result['Mean nDCG']:.4f}")

print(f"\nBest K: {best_k} (Mean nDCG = {best_mean_ndcg:.4f})")

# Fit the algorithm on the full training data with the best K
algo_uu_best = knn.UserUser(best_k)
algo_uu_full = Recommender.adapt(util.clone(algo_uu_best))
algo_uu_full.fit(train_data)
print(len(test_data['user']))
# Check the number of unique users in the test set
num_test_users = test_data['user'].nunique()
print(f"Number of unique users in the test set: {num_test_users}")
# Get the unique users from the test data
test_users = test_data.user.unique()
# Generate recommendations for the test users with batch processing

# Generate recommendations for the test users with batch processing
test_recs = batch.recommend(algo_uu_full, test_users, 10)
test_recs['Algorithm'] = 'UserUser'

# Evaluate the recommendations using the test set
test_rla = topn.RecListAnalysis()
test_rla.add_metric(topn.ndcg)
test_results = test_rla.compute(test_recs, test_data)

# Display the evaluation results
print(test_results.head())
print("NDCG mean for test set:", test_results.ndcg.mean())